name: Update theme in Osuny template
on:
  release:
    types:
      - prereleased
      - released
jobs:
  update_template_theme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          repository: osunyorg/template
          submodules: 'recursive'
          token: ${{ secrets.OSUNY_EXAMPLE_TOKEN }}

      - name: Set Git user
        run: |
          git config user.name osuny-bot
          git config user.email osuny@noesya.coop

      - name: Checkout submodule
        uses: actions/checkout@v4
        with:
          repository: osunyorg/theme
          token: ${{ secrets.OSUNY_EXAMPLE_TOKEN }}
          path: themes/osuny
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Pushing on template
        run: |
          git add .
          git commit -m "Update theme version to ${{ github.event.release.name }}."
          git push origin main
